[package]
name = "backtesting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "0.18.0"
serde = "1.0.130"
hyper = "0.14"
csv = "1.1"